config/routes.rb
Testapp::Application.routes.draw do
  get "download/file" #all types

  resources :comments


  resources :users do
	  match "/settings", to: "user_settings#index", via: :get
  end
  match '/signup', to: 'users#new', via: :get

  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete

	resources :genmenus
	match "/genmenus/:id" => "genmenus#submenuadd", via: :post

	resources :submenus

	resources :sm_contents do
		resources :assets
		match '/assets/edit' => 'assets#edit', :as => 'edit_assets', via: :get
		match '/assets/edit' => 'assets#destroy', via: :post


	end



	match 'sm_contents/create' => 'sm_contents#create', via: :post







	root  'static_pages#home'

	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'
	match '/admintools', to: 'static_pages#cnm',  via: 'get'










end

app/models/submenu.rb
class Submenu < ActiveRecord::Base
	belongs_to :genmenu
	#default_scope order: { :updated_at => :desc }
	has_many :sm_contents#, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true#, order: 'updated_at desc'
	accepts_nested_attributes_for :sm_contents

end

app/controllers/submenus_controller.rb
class SubmenusController < ApplicationController
	before_action :set_smenu, only: [:show, :edit, :update, :destroy]

	add_breadcrumb "home", :root_path

	def new
		@smenu = Submenu.new
		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @smenu }
		end
	end

  def create
	  @gmenu = Genmenu.find(params[:id])
	  @submenu = @gmenu.submenus.build(smenu_params)
	  @submenu.save
	  redirect_to @submenu
  end

  def destroy
  end

  def edit
	  @smenu = Submenu.find(params[:id])
  end

	def update
		@smenu = Submenu.find(params[:id])
		respond_to do |format|
			if @smenu.update_attributes(smenu_update_params)
				format.html { redirect_to @smenu.genmenu, notice: 'Second menu was successfully updated.' }
			else
				format.html { render action: "edit" }
			end
		end
	end

	def show
		@smenu = Submenu.find(params[:id])

		#add_breadcrumb "home", :root_path
		add_breadcrumb @smenu.sname, submenu_path(:id => @smenu.id)

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @smenu }
		end
	end

	#def SmContentAdd
	#	@smenu = Submenu.find(params[:id])
	#	@content = SmContent.new(get_content)
	#	#@content.testoptions.build

	#	respond_to do |format|
	#		if @content.save
	#			format.html { redirect_to @content, notice: 'Survey was successfully created.' }
	#			format.json { render action: 'show', status: :created, location: @content }
	#		else
	#			format.html { render action: 'new' }
	#			format.json { render json: @content.errors, status: :unprocessable_entity }
	#		end
	#	end
	#end

	private
  # Use callbacks to share common setup or constraints between actions.

	def get_content
		#params.require(:contents).permit(:title,:content,:attache)
		params.require(:sm_contents).permit(:id, :title, :content, :testoptions => [:option])

		#params.require(:survey).permit(:name,questions_attributes: [:content, :id, :survey_id,answers_attributes: [:content, :id, :questions_id]])
	end

	def get_opt
		#params.require(:contents).permit(:title,:content,:attache)
		params.require(:sm_contents).permit(:id, testoptions: [:option])

		#params.require(:survey).permit(:name,questions_attributes: [:content, :id, :survey_id,answers_attributes: [:content, :id, :questions_id]])
	end

	def get_smenu_id
		params.permit(:id)
	end

	def set_smenu
		@smenu = Submenu.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def smenu_params
		params.require(:submenu).permit(:sname, :genmenu_id)
	end

	def smenu_update_params
		params.require(:submenu).permit(:sname)
	end

end

app/helpers/submenus_helper.rb
module SubmenusHelper
	def get_active_submenu(smenu_id)
		submenu_id = params[:id]
		mclass = ''
		if params[:controller] == 'submenus'
			if submenu_id.to_i == smenu_id.to_i
				mclass = 'active'
			end
		end
		mclass
	end
end

app/views/submenus/_menu.html.erb
<span class="badge">
  <%= link_to "Edit", edit_submenu_path(@smenu.id), :method => :get, class: "my-link" %>
</span>
<span class="badge">
  <%= link_to "Destroy", submenu_path(@smenu.id), :method => :delete , class: "my-link", data: { confirm: 'Are you sure ?' } %>
</span>

app/views/submenus/create.html.erb
<h1>Submenus#create</h1>
<p>Find me in app/views/submenus/create.html.erb</p>

app/views/submenus/destroy.html.erb
<h1>Submenus#destroy</h1>
<p>Find me in app/views/submenus/destroy.html.erb</p>

app/views/submenus/edit.html.erb
<h1><%= @smenu.sname %> Edit</h1>

<%= form_for(@smenu) do |f| %>
  <% if @smenu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@smenu.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @smenu.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "sname", "Sub Menu name" %><br />
    <%= f.text_field :sname, :text => @smenu.sname %>
  </div>
  <div class="">
    <%= f.submit "Update", class: "btn" %>
  </div>
<% end %>

app/views/submenus/index.html.erb
<% if signed_in? && current_user.admin? %>
	find me in submenus/index.html.erb
	<p><%= @smenu.sname %> <%= render "menu" %></p>
<% end %>

<h3><%= @smenu.sname %></h3>

<% if signed_in? && current_user.admin? %>

	<div>
    <div class="actions">
      <p><%= link_to "Add Content", new_sm_content_path(:id => @smenu) %></p>
    </div>
	</div>

<% end %>

<%= will_paginate @smenu.sm_contents.paginate(page: params[:page], :per_page => 6) %>

<% @smenu.sm_contents.paginate(page: params[:page], :per_page => 6).each do |c| %>
  <div class="well-box-my">
    <div class="well-center-my">
      <div class="text-block">
        <div class="text-image-gradient"></div>
        <h3><%= c.title %></h3>
        <%= raw c.content %>
      </div>

      <p>
      <ol class="file-list">
        <% @assets = get_assets(c) %>
        <% @assets.each_with_index do |a,n| %>
          <li><%= link_to a.asset_file_name, a.asset.url %></li>
        <% end %>
      </ol>
      </p>
      <p><%= link_to "learn more", sm_content_path(c, submenu_id: c.submenu_id ), class: "btn btn-primary", :method => :get %></p>
    </div>
    <div class="well-foot-my"><%= time_ago_in_words c.updated_at %></div>
  </div>
<% end %>

<%= will_paginate @smenu.sm_contents.paginate(page: params[:page], :per_page => 6) %>

app/views/submenus/show.html.erb
<% if signed_in? && current_user.admin? %>
	find me in submenus/show.html.erb
	<p><%= @smenu.sname %> <%= render "menu" %></p>
	TEST STRING
<% end %>

<h4><%= @smenu.sname %></h4>

<% if signed_in? && current_user.admin? %>
	<div>
    <div class="actions">
      <p><%= link_to "Add Content", new_sm_content_path(:id => @smenu) %></p>
    </div>
	</div>
<% end %>

<%= will_paginate @smenu.sm_contents.paginate(page: params[:page], :per_page => 6), :previous_label => " « ", :next_label => " » " %>

<% @smenu.sm_contents.paginate(page: params[:page], :per_page => 6).each do |c| %>
  <section id="sm_contents_<%= c.id %>" class="section_content_block">
    <div class="well-foot-my">
      <%= time_ago_in_words c.updated_at %> <br/>
    </div>
    <div class="content-block">

      <div class="text-block">
        <div class="text-image-gradient"></div>
        <h4 style="border-bottom:1px solid #ededed; padding-bottom:10px" class="text"><%#= c.title %><%= link_to c.title, sm_content_path(c) %></h4>

        <div class="text-block-full">
          <%= c.content.html_safe %>
        </div>

      </div>



      <% @assets = get_assets(c) %>
      <% if @assets.count > 0 %>

        <div class="accordion" id="sm_contents_accordion_<%= c.id %>" style="padding-left: 10px; padding-right: 10px; padding-top:20px; padding-bottom: 0px; margin-bottom: 0px">
          <div class="accordion-group">
            <div class="accordion-heading">
              <div class="accordion-toggle" data-toggle="collapse" data-parent="#sm_contents_accordion_<%= c.id %>" onclick="js_show('#sm_contents_files_<%= c.id %>')">
                <span style="color:#3399ff; font-size: 13px;">показать файлы</span>
              </div>
            </div>

            <div id="sm_contents_files_<%= c.id %>" class="dropdown_box">
              <div class="accordion-inner">


                <ul class="file-list">
                  <% @assets.each_with_index do |opt,n| %>
                    <% if n % 2 == 0 %>
                      <li class="file-line"><span><%= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %></span></li>
                    <% end %>
                  <% end %>
                </ul>

                <ul class="file-list">
                  <% @assets.each_with_index do |opt,n| %>
                    <% if n % 2 != 0 %>
                      <li class="file-line"><span><%= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %></span></li>
                    <% end %>
                  <% end %>
                </ul>


              </div>
            </div>

          </div>
        </div>
      <% end %>




      <p class="well-foot-my02">
        <%= link_to "показать полностью", sm_content_path(c) %>
	      |
        <%= link_to "перейти к обсуждению", comment_path(c) %> (<%= c.comments.count %>)
      </p>
    </div>
    <!--<div class="well-foot-my"><%#= time_ago_in_words c.updated_at %></div>-->

  </section>
<% end %>

<%= will_paginate @smenu.sm_contents.paginate(page: params[:page], :per_page => 6), :previous_label => " « ", :next_label => " » " %>

<!--
  <div class="well-box-my">
    <div class="well-center-my">
      <div class="text-block">
        <div class="text-image-gradient"></div>
        <h3><%#= c.title %></h3>
        <%#= c.content.html_safe %>
      </div>

      <p>
        <ol class="file-list">
	        <%# @assets = get_assets(c) %>
<%# @assets.each_with_index do |opt,n| %>
            <li>
              <%#= link_to opt.asset_file_name, download_file_path(asset_id: opt.id)  %>
            </li>
          <%# end %>
        </ol>
      </p>
      <p><%#= link_to "learn more", sm_content_path(c), class: "btn btn-primary" %></p>
    </div>
    <div class="well-foot-my"><%#= time_ago_in_words c.updated_at %></div>
  </div>
-->

app/views/submenus/transfer.html.erb
<h1>Submenus#transfer</h1>
<p>Find me in app/views/submenus/transfer.html.erb</p>