config/routes.rb
Testapp::Application.routes.draw do
  get "download/file" #all types

  resources :comments


  resources :users do
	  match "/settings", to: "user_settings#index", via: :get
  end
  match '/signup', to: 'users#new', via: :get

  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete

	resources :genmenus
	match "/genmenus/:id" => "genmenus#submenuadd", via: :post

	resources :submenus

	resources :sm_contents do
		resources :assets
		match '/assets/edit' => 'assets#edit', :as => 'edit_assets', via: :get
		match '/assets/edit' => 'assets#destroy', via: :post


	end



	match 'sm_contents/create' => 'sm_contents#create', via: :post







	root  'static_pages#home'

	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'
	match '/admintools', to: 'static_pages#cnm',  via: 'get'










end

app/models/sm_content.rb
class SmContent < ActiveRecord::Base
	belongs_to :submenu
	has_many :comments

	default_scope order: { :updated_at => :desc }

	has_many :assets, :dependent => :destroy
	validates_length_of :content, :maximum => 10000
	accepts_nested_attributes_for :assets
end

app/controllers/sm_contents_controller.rb
class SmContentsController < ApplicationController
	#before_action only: [:show, :update, :destroy]

	add_breadcrumb "home", :root_path


  def index
	  @smc = SmContent.find_by_submenu_id(:submenu_id)

	  respond_to do |format|
		  format.html # index.html.erb
		  format.json { render json: @smc }
	  end
  end

  def show
		@smc = SmContent.find(params[:id])
		@submenu = Submenu.find(@smc.submenu_id)
		@submenu_id = @smc.submenu_id


		add_breadcrumb @submenu.sname, submenu_path(:id => @smc.submenu_id)
		add_breadcrumb @smc.title
  end

	def edit
		@smc = SmContent.find(params[:id])
		@submenu = Submenu.find(@smc.submenu_id)
		@submenu_id = @smc.submenu_id

		add_breadcrumb @submenu.sname, submenu_path(:id => @smc.submenu_id)
		add_breadcrumb @smc.title, sm_content_path(:id => @smc.id)
		add_breadcrumb "edit"
	end

	def update
		@smc = SmContent.find(params[:id])
		respond_to do |format|
			if @smc.update_attributes(content_update_params)
				format.html { redirect_to @smc, notice: 'Content was successfully updated.' }
			else
				format.html { render action: "edit" }
				#format.html { redirect_to @smc_error_page, notice: 'Content was successfully updated.' }
			end
		end
	end

	def destroy
		@smc = SmContent.find(params[:id])
		@submenu_id = @smc.submenu_id
		respond_to do |format|
			if @smc.destroy
				format.html { redirect_to submenu_path(@submenu_id), notice: 'Content was successfully deleted.' }
			else
				format.html { render action: "edit" }
			end
		end
	end

  def new
	  @sm_content = SmContent.new
	  @sm_content.assets.build
	  @submenu_id = params[:id]


  end

	def create
		@content = SmContent.new(get_content)
		@submenu_id = params[:submenu_id]

		respond_to do |format|
			if @content.save
				format.html { redirect_to sm_content_path(@content, params: {submenu_id: @content.submenu_id} ), notice: 'Content was successfully created.' }
				format.json { render action: 'show', status: :created, location: @content }
			else
				format.html { render action: 'new' }
				format.json { render json: @content.errors, status: :unprocessable_entity }
			end
		end
	end

	private
  def get_content
	  #params.require(:sm_content).permit(:title, :content, :submenu_id, assets_attributes: [:tempfile, :original_filename, :content_type, :headers])
	  #params.permit(:name, {:emails => []}, :friends => [ :name, { :family => [ :name ], :hobbies => [] }])
	  params.require(:sm_content).permit(:title, :content, :submenu_id, assets_attributes: [:asset])
  end

	def get_submenu_id
		params[:submenu_id]
	end

	def content_update_params
		params.require(:sm_content).permit(:title, :content, :submenu_id, assets_attributes: [:asset])
	end


end

app/helpers/sm_contents_helper.rb
module SmContentsHelper
end

app/views/sm_contents/create.html.erb
<h1>SmContents#create</h1>
<p>Find me in app/views/sm_contents/create.html.erb</p>

app/views/sm_contents/destroy.html.erb
<h1>SmContents#destroy</h1>
<p>Find me in app/views/sm_contents/destroy.html.erb</p>

app/views/sm_contents/edit.html.erb
<h3><%= @smc.title %> Edit</h3>

<%#= tinymce %>

<%= form_for @smc, html: { multipart: true } do |f| %>
  <% if @smc.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h3><%= pluralize(@smc.errors.count, "error") %> prohibited this post from being saved:</h3>

      <ul>
        <% @smc.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% else %>

  <div class="actions">
    <%= f.text_field :submenu_id, type: "hidden", value: @smc.submenu_id %>
    <%= f.text_field :title, placeholder: "Title", class: "span13", style: "min-width:200px", :text => @smc.title %>
  </div>


  <!--<div class="actions">
    <%#= f.text_area :content, placeholder: "Content text", :class => "tinymce", style: "min-width:200px;", :text => @smc.content %>
  </div>-->

  <div class="actions" style="border-bottom-right-radius:2px; border-top-right-radius: 2px;">
    <%= f.text_area :content, placeholder: "Content text", :id => "some-textarea", :class => "wysihtml5" %>

    <script type="text/javascript">
	    $(document).ready(function(){

		    $('.wysihtml5').each(function(i, elem) {
		      $(elem).wysihtml5();
        });

	    })
    </script>
  </div>



	<p>
    <div class="actions">
      <%= f.submit "Сохранить", class: "btn" %>
    </div>
	</p>
	<% end %>


<% end %>

app/views/sm_contents/index.html.erb
<h1>SmContents#index</h1>
<p>Find me in app/views/sm_contents/index.html.erb</p>

app/views/sm_contents/new.html.erb
<%= tinymce %>

<%= form_for(@sm_content, html: { multipart: true }) do |f| %>
  <%# if @smc.errors.any? %>
    <!-- <ul>
      <%# @smc.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
      <%# end %>
    </ul> -->
  <%# end %>

	<div class="actions">
    <%= f.text_field :submenu_id, type: "hidden", value: @submenu_id %>
    <%= f.text_field :title, placeholder: "Title", class: "span13", style: "min-width:200px" %>
	</div>



	<div class="actions" style="border-bottom-right-radius:2px; border-top-right-radius: 2px;">
    <%= f.text_area :content, placeholder: "Content text", :class => "tinymce", style: "min-width:200px;" %>
	</div>

  <!--<div class="actions" style="border-bottom-right-radius:2px; border-top-right-radius: 2px;">
    <%#= f.text_area :content, placeholder: "Content text", :id => "some-textarea", :class => "wysihtml5" %>

    <script type="text/javascript">

	    $(document).ready(function(){

		    $('.wysihtml5').each(function(i, elem) {
			    $(elem).wysihtml5();
		    });

	    });



    </script>
	</div>-->


	<p>
    <%= f.fields_for :assets do |asset_fields| %>
      <%# if asset_fields.object.new_record? %>
        <div class="actions">
          <%= asset_fields.file_field :asset, :multiple => true, :name => 'sm_content[assets_attributes][][asset]' %>
        </div>
      <%# end %>
    <% end %>
	</p>

	<p>
		<div class="actions">
      <%= f.submit "Create", class: "btn" %>
		</div>
	</p>
<% end %>

app/views/sm_contents/show.html.erb
<!--<div class="well-box-my">
  <div class="well-center-my">
    <div class="text-block-full">
      <div class="text-image-gradient2"></div>
      <h3><%#= @smc.title %></h3>
      <%#= raw @smc.content %>
	    <div class="text-block-full">
        <%#= @smc.content.html_safe %>
		  </div>
    </div>

	  <p>
		  <ol class="file-list">
		    <%# @smc.assets.each do |opt| %>
		      <li>
		        <%#= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %>
		      </li>
		    <%# end %>
			</ol>
	  </p>


    <p>
      <%#= link_to "Edit text", edit_sm_content_path(@smc), class: "btn btn-primary" %>
      <%#= link_to "Add files", new_sm_content_asset_path(@smc), class: "btn btn-primary" %>
      <%#= link_to "Delete files", sm_content_edit_assets_path(@smc), class: "btn btn-primary", :method => :get %>
      <%#= link_to "Delete All", sm_content_path, class: "btn btn-danger", :method => :delete, :confirm => "Вы уверены что хотите удалить эту статью полностью?" %>
    </p>

  </div>
  <div class="well-foot-my"><%#= time_ago_in_words @smc.updated_at %></div>
</div>-->


<section id="sm_contents_<%= @smc.id %>" class="section_content_block sm-content-show">
  <div class="well-foot-my">
    <%= time_ago_in_words @smc.updated_at %> <br/>
  </div>
  <div class="content-block">

    <div class="text-block2">
      <!--<div class="text-image-gradient"></div>-->
      <h4 style="border-bottom:1px solid #ededed; padding-bottom:10px" class="text"><%= @smc.title %></h4>

      <div class="text-block-full">
        <%= @smc.content.html_safe %>
      </div>

    </div>

    <% if @smc.assets.count > 0 %>

      <div class="accordion" id="sm_contents_accordion_<%= @smc.id %>" style="padding-left: 10px; padding-right: 10px; padding-top:20px; padding-bottom: 0px; margin-bottom: 0px">
        <div class="accordion-group">
          <div class="accordion-heading">
            <div class="accordion-toggle" data-toggle="collapse" data-parent="#sm_contents_accordion_<%= @smc.id %>" onclick="js_show('#sm_contents_files_<%= @smc.id %>')">
              <span style="color:#3399ff; font-size: 13px;">показать файлы</span>
            </div>
          </div>

          <div id="sm_contents_files_<%= @smc.id %>" class="dropdown_box">
            <div class="accordion-inner">

								<ul class="file-list">
                  <% @smc.assets.each_with_index do |opt,n| %>
                    <% if n % 2 == 0 %>
                      <li class="file-line"><span><%= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %></span></li>
                    <% end %>
                  <% end %>
	              </ul>

	              <ul class="file-list">
                  <% @smc.assets.each_with_index do |opt,n| %>
                    <% if n % 2 != 0 %>
                      <li class="file-line"><span><%= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %></span></li>
                    <% end %>
                  <% end %>
		            </ul>


            </div>
          </div>

        </div>
      </div>
    <% end %>




    <!--<p class="well-foot-my02">
      <span class="my-badge"><%#= link_to "Редактировать текст", edit_sm_content_path(@smc), class: "my-link" %></span>
      <span class="my-badge"><%#= link_to "Добавление файлов", new_sm_content_asset_path(@smc), class: "my-link" %></span>
      <span class="my-badge"><%#= link_to "Удаление файлов", sm_content_edit_assets_path(@smc), class: "my-link", :method => :get %></span>
      <span class="my-badge-danger"><#%= link_to "Удалить публикацию полностью", sm_content_path, class: "my-link-danger", :method => :delete, :confirm => "Вы уверены что хотите удалить эту статью полностью?" %></span>
    </p>-->


    <p class="well-foot-my02">
      <% if signed_in? && current_user.admin? %>
        <%= link_to "Редактировать текст", edit_sm_content_path(@smc) %> |
        <%= link_to "Добавление файлов", new_sm_content_asset_path(@smc) %> |
        <%= link_to "Удаление файлов", sm_content_edit_assets_path(@smc), :method => :get %> |
        <%= link_to "Удалить публикацию полностью", sm_content_path, :method => :delete, :confirm => "Вы уверены что хотите удалить эту статью полностью?" %> |
      <% end %>
      <%= link_to "обсуждения", comment_path(@smc) %> (<%= @smc.comments.count %>)
    </p>
  </div>

</section>