config/routes.rb
Testapp::Application.routes.draw do
  get "download/file" #all types

  resources :comments


  resources :users do
	  match "/settings", to: "user_settings#index", via: :get
  end
  match '/signup', to: 'users#new', via: :get

  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete

	resources :genmenus
	match "/genmenus/:id" => "genmenus#submenuadd", via: :post

	resources :submenus

	resources :sm_contents do
		resources :assets
		match '/assets/edit' => 'assets#edit', :as => 'edit_assets', via: :get
		match '/assets/edit' => 'assets#destroy', via: :post


	end



	match 'sm_contents/create' => 'sm_contents#create', via: :post







	root  'static_pages#home'

	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'
	match '/admintools', to: 'static_pages#cnm',  via: 'get'










end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :check_admin, only: :cnm

	add_breadcrumb "home", :root_path
	#add_breadcrumb "submenus", submenus_path
	#add_breadcrumb "content", sm_contents_path

  def home
	  #@genmenusall = Genmenu.all
  end

  def about
	  #@genmenusall = Genmenu.all
  end

  def contact
	  #@genmenusall = Genmenu.all
  end

  def help
	  #@genmenusall = Genmenu.all
  end

	def cnm
		#@genmenusall = Genmenu.all
		add_breadcrumb "admin tools", admintools_path
	end

	private
	def check_admin
		redirect_to(root_url) unless current_user.admin?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#About</h1>
<p>Find me in app/views/static_pages/About.html.erb</p>

app/views/static_pages/cnm.html.erb
<h1>Admin Tools</h1>

<p><%= link_to "Edit main menu", genmenus_path %></p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#Contact</h1>
<p>Find me in app/views/static_pages/Contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>Help Page</h1>

app/views/static_pages/home.html.erb
<h3>Home page</h3>

<%= will_paginate @allcontent.paginate(page: params[:page], :per_page => 6), :previous_label => " « ", :next_label => " » " %>

<% @allcontent.paginate(page: params[:page], :per_page => 6).each do |c| %>
  <section id="sm_contents_<%= c.id %>" class="section_content_block">
    <div class="well-foot-my">
      <%= time_ago_in_words c.updated_at %> <br/>
    </div>

    <div class="content-block">

      <div class="text-block">
        <div class="text-image-gradient"></div>
        <h4 style="border-bottom:1px solid #ededed; padding-bottom:10px" class="text"><%#= c.title %><%= link_to c.title, sm_content_path(c) %></h4>

        <div class="text-block-full">
          <%= c.content.html_safe %>
        </div>

      </div>



      <% @assets = get_assets(c) %>
	    <% if @assets.count > 0 %>

        <div class="accordion" id="sm_contents_accordion_<%= c.id %>" style="padding-left: 10px; padding-right: 10px; padding-top:20px; padding-bottom: 0px; margin-bottom: 0px">
          <div class="accordion-group">
            <div class="accordion-heading">
              <div class="accordion-toggle" data-toggle="collapse" data-parent="#sm_contents_accordion_<%= c.id %>" onclick="js_show('#sm_contents_files_<%= c.id %>')">
                <span style="color:#3399ff; font-size: 13px;">показать файлы</span>
              </div>
            </div>

            <div id="sm_contents_files_<%= c.id %>" class="dropdown_box">
              <div class="accordion-inner">


                <ul class="file-list">
                  <% @assets.each_with_index do |opt,n| %>
                    <% if n % 2 == 0 %>
                      <li class="file-line"><span><%= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %></span></li>
                    <% end %>
                  <% end %>
                </ul>

                <ul class="file-list">
                  <% @assets.each_with_index do |opt,n| %>
                    <% if n % 2 != 0 %>
                      <li class="file-line"><span><%= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %></span></li>
                    <% end %>
                  <% end %>
                </ul>


              </div>
            </div>

          </div>
        </div>
		  <% end %>




      <p class="well-foot-my02">
        <%= link_to "показать полностью", sm_content_path(c) %>
        |
        <%= link_to "перейти к обсуждению", comment_path(c) %> (<%= c.comments.count %>)
      </p>
    </div>
    <!--<div class="well-foot-my"><%#= time_ago_in_words c.updated_at %></div>-->

  </section>
<% end %>

<%= will_paginate @allcontent.paginate(page: params[:page], :per_page => 6), :previous_label => " « ", :next_label => " » " %>


<!--
<div class="well-box-my">
    <div class="well-center-my">

      <div class="text-block">
        <div class="text-image-gradient"></div>
        <h3><%#= c.title %></h3>

        <div class="text-block-full">
          <%#= c.content.html_safe %>
        </div>

      </div>

	    <p>
		    <ol class="file-list">
			    <%# @assets = get_assets(c) %>
<%# @assets.each_with_index do |opt,n| %>
            <li>
              <%#= link_to image_tag(asset_fields.object.asset.url(:thumb)), asset_fields.object.asset.url(:original) %>
  <%#= link_to opt.asset_file_name, opt.asset.url  %>
  <%#= link_to opt.asset_file_name, download_file_path(:asset_id => opt.id) %>

            </li>
          <%# end %>
			  </ol>
	    </p>
      <p><%#= link_to "learn more", sm_content_path(c), class: "btn btn-primary" %></p>
    </div>
    <div class="well-foot-my"><%#= time_ago_in_words c.updated_at %></div>
  </div>
-->


