config/routes.rb
Testapp::Application.routes.draw do
  get "download/file" #all types

  resources :comments


  resources :users do
	  match "/settings", to: "user_settings#index", via: :get
  end
  match '/signup', to: 'users#new', via: :get

  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: :get
  match "/signout", to: "sessions#destroy", via: :delete

	resources :genmenus
	match "/genmenus/:id" => "genmenus#submenuadd", via: :post

	resources :submenus

	resources :sm_contents do
		resources :assets
		match '/assets/edit' => 'assets#edit', :as => 'edit_assets', via: :get
		match '/assets/edit' => 'assets#destroy', via: :post


	end



	match 'sm_contents/create' => 'sm_contents#create', via: :post







	root  'static_pages#home'

	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'
	match '/admintools', to: 'static_pages#cnm',  via: 'get'










end

app/models/asset.rb
class Asset < ActiveRecord::Base
	belongs_to :sm_content
	attr_accessor :assets, :original_filename, :content_type, :tempfile, :headers
	has_attached_file :asset#,
	                  #:path => ":rails_root/public/system/:asset/:id/:filename",
	                  #:url => "/system/:asset/:id/:filename"

	validates_attachment_content_type :asset, :content_type =>
		[ 'multipart/form-data',
		  'image/png',
		  'image/jpeg',
		  'image/gif',
		  'image/jpg',
		  'image/bmp',
		  'text/plain',
		  'application/pdf',
		  #'application/octet-stream',
		  'application/zip',
		  'application/msword',
		  'application/vnd.ms-excel',
		  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
		  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			'application/x-msdownload'
		]
	#validates_something_else
	#validates_attachment :asset, #, :presence => true,
	#do_not_validate_attachment_file_type :asset
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :sm_content
	belongs_to :user

	default_scope order: { :updated_at => :desc }
end

app/models/genmenu.rb
class Genmenu < ActiveRecord::Base
	has_many :submenus, :dependent => :destroy
	accepts_nested_attributes_for :submenus
end

app/models/sm_content.rb
class SmContent < ActiveRecord::Base
	belongs_to :submenu
	has_many :comments

	default_scope order: { :updated_at => :desc }

	has_many :assets, :dependent => :destroy
	validates_length_of :content, :maximum => 10000
	accepts_nested_attributes_for :assets
end

app/models/submenu.rb
class Submenu < ActiveRecord::Base
	belongs_to :genmenu
	#default_scope order: { :updated_at => :desc }
	has_many :sm_contents#, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true#, order: 'updated_at desc'
	accepts_nested_attributes_for :sm_contents

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 30 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }


	validates :password, length: { minimum: 6, maximum: 12 }
	has_secure_password

	has_many :comments
	belongs_to :user_setting


	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end

end

app/models/user_setting.rb
class UserSetting < ActiveRecord::Base
	belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_action :signed_in_user, only: [:edit, :update, :destroy]
	before_action :correct_user,   only: [:edit, :update, :destroy]
	before_action :admin_user,     only: :destroy

	add_breadcrumb "home", :root_path

	def show
		@user = User.find(params[:id])

		add_breadcrumb "users", users_path#, submenu_path(:id => @smc.submenu_id)
		add_breadcrumb @user.name
	end

	def edit
		@user = User.find(params[:id])
	end

	def settings

	end

	def update

	end

	def index
		@users = User.all

		add_breadcrumb "users"
	end

	def new
		@user = User.new
		add_breadcrumb "sign up"
	end

	def create
		@user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))

		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			render 'users/new'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted."
		redirect_to users_url
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def signed_in_user
			redirect_to signin_url, notice: "Please sign in." unless signed_in?
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_url) unless signed_in? && current_user?(@user)
		end

		def admin_user
			redirect_to(users_url) unless current_user.admin?
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Page name"
		#base_title.to_s.force_encoding("UTF-8")
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def get_route
		path = Rails.application.routes.recognize_path(request.env['PATH_INFO'])

		controller = path[:controller]
		action = path[:action]
		controller
		#Rails::ActiveRecord.
	end

	def get_assets(content)
		@assets = Asset.where(:sm_content_id => content)
	end

	def mainmenubuild(main_menu_items)

	end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/generalpages_helper.rb
module GeneralpagesHelper
end

app/helpers/genmenus_helper.rb
module GenmenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
		cookies.delete(:remember_token)

		#cookies.delete(:last_uri)
		#cookies.delete(:current_request)
		#cookies.delete(:target_page)

		#cookies[:last_uri] = nil
		#cookies[:current_request] = nil
		#cookies[:target_page] = nil

		#session.delete(:last_uri)
		#session.delete(:current_request)
		#session.delete(:target_page)

		#session[:last_uri] = nil
		#session[:current_request] = nil
		#session[:target_page] = nil

		self.current_user = nil
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/sm_contents_helper.rb
module SmContentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/submenus_helper.rb
module SubmenusHelper
	def get_active_submenu(smenu_id)
		submenu_id = params[:id]
		mclass = ''
		if params[:controller] == 'submenus'
			if submenu_id.to_i == smenu_id.to_i
				mclass = 'active'
			end
		end
		mclass
	end
end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def full_title(page_title)
		base_title = "Page name"
		#base_title.to_s.force_encoding("UTF-8")
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/views/layouts/_footer.html.erb
  <div class="container footer-nav" style="">
    <small class="navbar-text">
      Test App By VS
    </small>
    <ul class="pull-right navbar-text">
      <li><%= link_to "About",   about_path, class: "navbar-btn" %></li>
      <li><%= link_to "Contact", contact_path, class: "navbar-btn" %></li>
    </ul>
    <%= debug(params) if Rails.env.development? %>
  </div>

app/views/layouts/_genmenu.html.erb
<div class="btn-group"><!-- <div class="btn-group"> -->
  <!-- <button class="btn btn-primary">Menu<span class="caret"></span></button> -->
  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Menu<span class="caret"></span></button>


	<ul class="dropdown-menu span6">

    <li class="column-menu span3">
      <ul>
        <% @main_menu_items.each_with_index do |menu,n| %>
          <% if n % 2 == 0 %>
            <li class="nav-header my-gen-menu-name"><span><%= menu.genmenuname %></span></li>
            <% menu.submenus.each do |smenu| %>
            <li><%= link_to smenu.sname, [menu, smenu] %></li>
            <% end %>
          <% end %>
				<% end %>
      </ul>
    </li>

    <li class="column-menu span3">
      <ul>
        <% @main_menu_items.each_with_index do |menu,n| %>
          <% if n % 2 != 0 %>
            <li class="nav-header my-gen-menu-name"><span><%= menu.genmenuname %></span></li>
            <% menu.submenus.each do |smenu| %>
              <li><%= link_to smenu.sname, [menu, smenu] %></li>
            <% end %>
          <% end %>
				<% end %>
      </ul>
    </li>

  </ul>

</div>

app/views/layouts/_genmenu2.html.erb
<div class="btn-group pull-right"><!-- <div class="btn-group"> -->
  <!-- <button class="btn btn-primary">Menu<span class="caret"></span></button> -->
  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Menu<span class="caret"></span></button>


  <ul class="dropdown-menu span6">

    <li class="column-menu span3">
      <ul>
        <% @main_menu_items.each_with_index do |menu,n| %>
          <% if n % 2 == 0 %>
            <li class="nav-header my-gen-menu-name"><span><%= menu.genmenuname %></span></li>
            <% menu.submenus.each do |smenu| %>
              <li><%= link_to smenu.sname, smenu %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </li>

    <li class="column-menu span3">
      <ul>
        <% @main_menu_items.each_with_index do |menu,n| %>
          <% if n % 2 != 0 %>
            <li class="nav-header my-gen-menu-name"><span><%= menu.genmenuname %></span></li>
            <% menu.submenus.each do |smenu| %>
              <li><%= link_to smenu.sname, smenu %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </li>

  </ul>

</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top my-navbar-inverse">
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner "> -->

    <div class="container">
      <%= link_to "TEST APP", root_path, id: "logo" %>
      <nav>

        <% if signed_in? and current_user.admin? %>
          <ul class="nav pull-left">
            <li><%= link_to "Admin Tools", admintools_path %></li>
          </ul>
		    <% end %>

        <ul class="nav nav-pills">

          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Users",    users_path %></li>

	        <% if signed_in? %>

            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">My profile<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My page", current_user %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>

		      <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Sign up", signup_path %></li>
		      <% end %>

          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>

        <%= render 'layouts/genmenu2' %>
        <%#= render 'layouts/genmenu' %>

      </nav>
    </div>
  </div>
<!--</header>-->

app/views/layouts/_leftbar.html.erb
  <div class="span3">
    <% if @main_menu_items.count > 0 %>
    <div class="my-well sidebar-nav">
      <ul class="nav nav-list">
        <% @main_menu_items.each_with_index do |menu,n| %>
          <li class="nav-header"><%= menu.genmenuname %></li>
          <% menu.submenus.each do |smenu| %>
            <li class="<%= get_active_submenu(smenu.id) %>">
              <%= link_to smenu.sname, smenu %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html" charset="utf-8">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= tinymce_assets %>
  <%= render 'layouts/shim' %>
</head>
<body style="background:#ffffff;">

	<%= render 'layouts/header' %>

	<div class="wrap container-fluid" style="margin-bottom:220px; background:#ffffff">

		<div class="row-fluid">

		  <%= render "layouts/leftbar" %>

	    <div class="span6" style="background:#FFF; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; padding-bottom:10px;">
	      <ol class="breadcrumb">
	        <%= render_breadcrumbs :tag => :li, :separator => " <span class=\"breadcrumb-separator\"> » </span> " %>
	      </ol>

	      <% if signed_in? && current_user.admin? %> <%# || Rails.env.development? %>
	        <div class="alert">
	          Session last URI<br /><%= session[:last_uri] %><br />
		        Session current URI<br /><%= session[:current_uri] %><br />
		        Session target page<br /><%= session[:target_page] %>
	        </div>
	      <% end %>

	      <%# flash.each do |key, value| %>
	        <!--<div class="alert alert-<%#= key %>"><%#= value %></div> -->
	      <%# end %>

	      <% flash.each do |key, value| %>
	        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	      <% end %>

	      <%= yield %>
	    </div>

		  <!--<div class="span3">
		    <div class="well sidebar-nav">
		      <ul class="nav nav-list">
		        <li class="nav-header">Sidebar</li>
		        <li class="active"><a href="#">Link</a></li>
		        <li><a href="#">Link</a></li>
		        <li><a href="#">Link</a></li>
		        <li><a href="#">Link</a></li>
		      </ul>
		    </div>
		  </div> -->

		</div>

	</div>


	<div class="navbar navbar-fixed-bottom" style="z-index: -1; background:#000000; padding-left:20px; padding-right:20px;">
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>